### ISSUE TITLE
针对于作者说注释中"可能的问题： 仅支持x64 ，目前仅完美支持win10及以上，x64架构 不会有人2023年了还在用win7/x86吧"

### ISSUE THREAD

**Issue by Xiaoan6666** [yige-yigeren/rdpwrap_AutoUpdate_CN#2]
可能的问题：
仅支持x64 ，目前仅完美支持win10及以上，x64架构
不会有人2023年了还在用win7/x86吧

现在80%以上的工作室用的还是Windows7系统，一些特殊行业例如我这个行业，4W+  1H2G的Windows 7  32位的系统。

**Comment by wuyilingwei** [comment]
嗯，我这个项目主要是针对的就是个人的单工作机计划，以单高性能机提供城际范围的手机/平板连接用。

另外就是之前的脚本就是仅测试win7的，我懒得检查兼容性了，我手头上目前在使用的也仅仅有win10/11的，也没法做兼容性测试。写这个本来就是个人用

另外根据系统生命周期，win7及x86已经微软都不提供更新了，我属实不想废哪个劲

有需要可以自己直接改源码

**Comment by wuyilingwei** [comment]
![image](https://github.com/yige-yigeren/rdpwrap_AutoUpdate_CN/assets/53390868/42c7a4e3-13b1-4ae4-a050-70e8956a153c)

我在readme写了原因的

这句话只是一个吐槽，我不想一个随手改的玩意我还得去测试兼容性

**Comment by wuyilingwei** [comment]
好好说话不行吗，我给你骂人的删了
